name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/caiopilon/hello-world-docker:latest
          docker run ghcr.io/caiopilon/hello-world-docker:latest
          docker push ghcr.io/caiopilon/hello-world-docker:latest